const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, BorderStyle, ShadingType,
} = require('docx');
const fs = require('fs');

const TITLE = '図書館で借りた本の余白に、知らない誰かの文字があった。「ここが試験に出る」——【実話・感動】';

function h(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text, font: 'Arial', size: 28, bold: true, color: '2E4A7A' })] });
}
function p(text, opts = {}) {
  return new Paragraph({ spacing: { after: 160 },
    children: [new TextRun({ text, font: 'Arial', size: 22,
      bold: opts.bold||false, color: opts.color||'222222', italics: opts.italic||false })] });
}
function note(text) {
  return new Paragraph({ spacing: { after: 120, before: 80 },
    border: { left: { style: BorderStyle.SINGLE, size: 12, color: 'E07B39', space: 8 } },
    indent: { left: 240 },
    children: [new TextRun({ text: '【演出メモ】' + text, font: 'Arial', size: 20, color: 'E07B39', italics: true })] });
}
function hook(text) {
  return new Paragraph({ spacing: { after: 120, before: 80 },
    shading: { fill: 'FFF3E0', type: ShadingType.CLEAR },
    children: [new TextRun({ text: '🔒 ' + text, font: 'Arial', size: 20, bold: true, color: 'C0392B' })] });
}
function peak(num, text) {
  return new Paragraph({ spacing: { after: 120, before: 80 },
    shading: { fill: 'E8F4FD', type: ShadingType.CLEAR },
    children: [new TextRun({ text: `💡 感情ピーク${num}｜${text}`, font: 'Arial', size: 20, bold: true, color: '1A6FA8' })] });
}
function motif(text) {
  return new Paragraph({ spacing: { after: 120, before: 80 },
    shading: { fill: 'F0F7E8', type: ShadingType.CLEAR },
    children: [new TextRun({ text: '🎵 ' + text, font: 'Arial', size: 20, bold: true, color: '2E7A2E' })] });
}
function blank() { return new Paragraph({ spacing: { after: 80 }, children: [new TextRun('')] }); }

const children = [
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 },
    children: [new TextRun({ text: '感動系YouTube台本（v3・4000字以上拡張版）', font: 'Arial', size: 36, bold: true, color: '1A1A2E' })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 },
    children: [new TextRun({ text: TITLE, font: 'Arial', size: 22, bold: true, color: '2E4A7A' })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 300 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '2E75B6', space: 4 } },
    children: [new TextRun({ text: 'v3拡張：各シーン深掘り・五感描写追加・サラの内面拡充・締め行動CTAを具体化 / 約4,500文字', font: 'Arial', size: 20, color: 'C0392B' })] }),

  h('■ 作品情報'),
  p('ジャンル：無名の献身'),
  p('登場人物：エマ・クラーク（大学院生・28歳）／サラ・トンプソン（先輩・数年前に同課程修了）'),
  p('舞台：イギリス・ロンドン大学、2018年〜'),
  p('モチーフ：ページをめくる音「パラ……パラ……」（冒頭・中盤・終盤の3回）'),
  p('注記：語り継がれている実話をもとにした物語として構成。', { color: '888888' }),
  blank(),

  h('◆ フェーズ①：フック（冒頭3〜8秒）'),
  note('BGM：完全無音。薄い紙のページをめくるSEのみ。説明ゼロ。'),
  motif('モチーフ①登場：ページをめくる音'),
  blank(),
  p('パラ……パラ……'),
  blank(),
  p('深夜の図書館。'),
  p('蛍光灯の白い光だけが、静まり返った部屋を照らしていた。'),
  p('外はとっくに暗くなっている。窓の向こうに、ロンドンの街灯が見えた。'),
  blank(),
  p('山積みの参考書。飲みかけのコーヒー。疲れた目。'),
  blank(),
  p('女性の手が、ある1ページで止まった。'),
  blank(),
  p('余白に、文字があった。'),
  blank(),
  p('鉛筆で、ていねいに書かれた文字。'),
  blank(),
  p('「ここが試験に出る。この定義だけは覚えて」', { bold: true }),
  blank(),
  p('彼女は、その文字を書いた人を知らなかった。'),
  p('名前も、顔も、いつ書かれたのかも。'),
  p('ただ——その文字だけが、そこにあった。'),
  blank(),
  p('それでも——その文字が、彼女の人生を変えた。', { bold: true }),
  blank(),

  h('◆ フェーズ②：背景（エマの孤独な受験生活）'),
  note('BGM：静かなピアノ。深夜感のある、少し疲れた温度感。'),
  blank(),
  p('2018年、ロンドン大学の大学院。'),
  blank(),
  p('エマ・クラークは、法学部の博士課程に在籍していた。'),
  p('28歳。イングランド北部の、小さな炭鉱の町の出身だった。'),
  p('祖父は炭鉱夫で、父はトラック運転手だった。'),
  p('大学に行った家族は、エマが初めてだった。'),
  p('奨学金だけを頼りに、一人でロンドンに来た。'),
  p('大きなスーツケースと、田舎の図書館で読み続けた本の知識だけを持って。'),
  blank(),
  p('周りの学生は、裕福な家庭の出身が多かった。'),
  p('親が弁護士。叔父が判事。幼いころから家に法律書が並んでいた、という同期もいた。'),
  p('そういう人たちが、当然のように席に座っていた。'),
  blank(),
  p('エマには、それがなかった。'),
  p('だからこそ、一冊の本を誰よりも丁寧に、最後まで読んだ。', { bold: true }),
  p('だからこそ、誰よりも早く図書館に来て、誰よりも遅く帰った。'),
  blank(),
  p('大学院の最初の1年は、ただ生き延びることだった。'),
  p('朝9時に授業が始まり、夜11時まで図書館にいた。'),
  p('アパートに帰れば、シャワーを浴びて、そのまま倒れるように眠った。'),
  p('友人と呼べる人間は、ほとんどいなかった。'),
  p('週末に誰かと食事をしたことも、映画を観に行ったことも、一度もなかった。'),
  blank(),
  p('それでも、やめようとは思わなかった。'),
  p('「ここまで来たんだから」——それだけを、毎晩自分に言い聞かせた。'),
  blank(),
  p('そして——1年目の終わりに、関門が待っていた。'),
  blank(),
  p('博士課程の「資格試験」。これに落ちると、課程を続けられない。'),
  p('研究室を去らなければならない。毎年、受験者の半数近くが脱落すると言われていた。'),
  blank(),
  hook('離脱防止フック①｜試験まで、あと3日というその夜——エマは限界だった。'),
  blank(),
  p('テキストを読んでいても、頭に入らなかった。'),
  p('目が、同じ行を何度も追っていた。コーヒーは4杯目だった。'),
  p('それでも眠気は消えなかった。'),
  blank(),
  p('「もうだめかもしれない」——そう思ったのは、その夜が初めてだった。'),
  blank(),

  h('◆ フェーズ③：試練・選択（余白の文字との出会い）'),
  note('BGM：ピアノが止まる。無音の緊張感。'),
  blank(),
  p('それでも図書館を出なかった。'),
  p('棚の端に残っていた、まだ読んでいない一冊を手に取った。'),
  blank(),
  p('「国際条約法の基礎」——分厚い、古い本だった。'),
  p('表紙は擦れ、背表紙はひびが入っていた。インクの染みがついたページもあった。'),
  p('何年も前から、この棚にあったのだろう。'),
  blank(),
  p('読み始めて、すぐに気づいた。余白に、文字がある。'),
  blank(),
  p('鉛筆で書かれた、細かい文字。ページをめくるたびに、現れる。'),
  blank(),
  p('パラ……パラ……', { bold: true }),
  blank(),
  p('「第3章の定義は逐語で覚えること。言い換えは減点になる」'),
  p('「この判例は毎年出る。事実関係を正確に押さえろ」'),
  p('「ここは読まなくていい。試験範囲外。時間の無駄になる」'),
  p('「第7章は必ず2問出る。軽く見るな」'),
  blank(),
  p('一部の文字は薄く消された跡があった。'),
  p('おそらく、誰かが返却前に消そうとしたのだろう。それでも、まだ読めた。'),
  p('ランプの下で目を細めると、すべての文字が、ちゃんとそこにあった。'),
  blank(),
  p('誰かが、丁寧に道を作っていた。'),
  blank(),
  p('エマは3時間、その書き込みを追いかけた。'),
  p('指でなぞりながら、ノートに書き写した。'),
  p('書き込みは、ただの感想ではなかった。'),
  p('どこが出るか、どこは飛ばしていいか、どの表現が減点になるか——'),
  p('試験を受けた人間だけが知っていることが、ていねいに書かれていた。'),
  blank(),
  p('その夜は初めて、「やれるかもしれない」と思えた。'),
  blank(),

  peak('①', '試験当日——「あの書き込みの通りだ」'),
  blank(),
  p('試験当日。会場に入ると、周りの学生たちの顔が強張っていた。'),
  p('エマも、手が少し震えていた。'),
  blank(),
  p('問題用紙を開いた瞬間、エマは息を呑んだ。'),
  blank(),
  p('「第3章の定義」が出ていた。'),
  p('あの書き込みが示した判例が出ていた。'),
  p('「ここは読まなくていい」と書かれた箇所は、一問も出ていなかった。'),
  p('第7章から、2問出ていた。'),
  blank(),
  p('ペンが動いた。止まらなかった。'),
  blank(),
  p('答案を書きながら、エマは何度も思った。'),
  p('あの文字を書いた人は、誰なのか。なぜ余白に残したのか。なぜ名前を書かなかったのか。'),
  blank(),
  p('結果が出た。合格だった。'),
  blank(),
  p('翌日、エマは図書館に向かった。あの本を抱えて、受付カウンターに立った。'),
  p('「この本を過去に借りた方のリストを見せてもらえますか」'),
  blank(),
  p('司書は困った顔をした。「個人情報の問題で、それはお見せできないんです」'),
  blank(),
  p('エマは頭を下げた。'),
  p('「この書き込みをした人に、お礼が言いたいんです。お願いです」'),
  blank(),
  p('司書は申し訳なさそうに言った。「気持ちはわかります。でも規則ですので……」'),
  blank(),
  hook('離脱防止フック②｜でも、司書は首を縦に振らなかった。そして——本当の探索が始まった。'),
  blank(),

  h('◆ フェーズ④：真実の発覚（探索とサラとの出会い）'),
  note('BGM：少し希望のある音色。探索のテンポ。ゆっくりと高まる。'),
  blank(),
  p('エマはその日から、別の方法で探し始めた。'),
  blank(),
  p('書き込みの字体を写真に撮り、法学部の掲示板に貼った。'),
  p('SNSにも投稿した。法学部の同期に片っ端から聞いた。'),
  p('大学のコミュニティフォーラムに書き込み、卒業生グループにも転送してもらった。'),
  blank(),
  p('通知を確認した。何もなかった。'),
  p('また確認した。何もなかった。'),
  p('また確認した。また確認した。'),
  blank(),
  p('1週間が過ぎた。2週間が過ぎた。'),
  blank(),
  p('「もしかして、もう見つからないかもしれない」——そう思い始めた頃。'),
  blank(),
  p('一通のメッセージが届いた。'),
  blank(),
  p('差出人は法学部の卒業生だという。'),
  p('「あなたが探している書き込みは、もしかしたらサラかもしれない」'),
  blank(),
  p('サラ・トンプソン。数年前に同じ博士課程を修了し、'),
  p('今は地方の法律援助機関で、お金のない依頼者のために働いているという。'),
  blank(),
  p('エマは震える手でメッセージを打った。'),
  p('「サラさんに連絡を取る方法を教えてもらえますか。直接お礼を言いたいんです」'),
  blank(),

  peak('②', 'サラからのメッセージ——「まさか誰かが気づくとは」'),
  blank(),
  p('数日後、サラ本人からメッセージが届いた。'),
  blank(),
  p('「あの書き込みのことで連絡をくれたのですね。'),
  p('まさか誰かが気づくとは思っていませんでした」'),
  blank(),
  p('エマは電話を申し込んだ。サラはすぐに承諾した。'),
  blank(),
  p('電話が繋がった瞬間、エマは言葉が出なかった。'),
  p('何を言えばいいか、何度も練習してきたはずなのに、声が、出なかった。'),
  blank(),
  p('やっと、絞り出した。'),
  p('「あなたの書き込みで、私は試験に合格しました。ありがとうございます」'),
  blank(),
  p('電話の向こうで、少し間があった。それからサラは言った。'),
  blank(),

  peak('③', 'サラの告白——「だから、本に書いた」'),
  note('BGM：クライマックス。ピアノとストリングスの重なり。'),
  blank(),
  p('「私も、あの試験で一度落ちたんです。', { italic: true, bold: true }),
  p('1回目の試験が終わった後、1人でアパートに帰って、床に座り込んだまま動けなかった。', { italic: true, bold: true }),
  p('泣く気力もなかった。ただ、天井を見上げていた。', { italic: true, bold: true }),
  blank(),
  p('2回目で合格したとき、自分が苦労したことを誰かに伝えたかった。', { italic: true, bold: true }),
  p('どこが本当に大事で、どこは捨てていいか。', { italic: true, bold: true }),
  p('そういうことを知っていれば、もっと楽だったと思っていたから。', { italic: true, bold: true }),
  blank(),
  p('でも、後輩を知らなかった。誰に話せばいいかも分からなかった。', { italic: true, bold: true }),
  p('それに——知っている人に教えるのは、なんだか違う気がした。', { italic: true, bold: true }),
  p('特定の誰かではなく、この試験で苦しんでいる、見知らぬ誰かに届けたかった。', { italic: true, bold: true }),
  blank(),
  p('だから、本に書いた。', { italic: true, bold: true }),
  blank(),
  p('図書館の本なら、いつか誰かが読むと思って。', { italic: true, bold: true }),
  p('その誰かが、少しでも楽になればと思って。', { italic: true, bold: true }),
  p('名前なんて、関係なかった。', { italic: true, bold: true }),
  p('ただ、誰かの役に立てばいいと思っていた」', { italic: true, bold: true }),
  blank(),
  p('エマは、声が出なかった。電話口で、泣いていた。'),
  blank(),
  p('サラが続けた。'),
  blank(),
  p('「でも正直に言うと、誰も気づかないだろうと思っていた。', { italic: true }),
  p('ただの落書きだと思って、消して返却する人がほとんどだろうと。', { italic: true }),
  p('あなたが連絡をくれたとき、最初は信じられなかった」', { italic: true }),
  blank(),
  p('少し間があった。電話の向こうで、風の音がした。'),
  blank(),
  p('「あなたが合格したと聞いて——私も報われた気がします。', { italic: true }),
  p('あの夜、本に書いてよかった」', { italic: true }),
  blank(),
  p('——しばらく、二人とも何も言わなかった。', { italic: true, color: '555555' }),
  blank(),

  motif('モチーフ③回収：ページをめくる音'),
  blank(),
  p('その夜、エマはあの本をもう一度開いた。'),
  blank(),
  p('パラ……パラ……', { bold: true }),
  blank(),
  p('見慣れた余白の文字たちが、今は違って見えた。'),
  blank(),
  p('これは、ただのメモではなかった。'),
  blank(),
  p('1度試験に落ちた誰かが、床に座り込んだまま動けなかった夜があって、'),
  p('立ち直って、合格して、それでも忘れられなかったから、'),
  p('次に来る、顔も名前も知らない誰かのために残していったもの。'),
  blank(),
  p('そういうものだった。'),
  blank(),
  p('エマはゆっくりとページを閉じた。本の表紙を、両手でそっと持った。'),
  blank(),
  p('「ありがとう」——声に出して、言った。誰にも聞こえない声で。でも、ちゃんと言った。'),
  blank(),

  h('◆ フェーズ⑤：余韻・締め・CTA'),
  note('BGM：静かにピアノへ戻る。フェードアウト。'),
  blank(),

  peak('④', '視聴者への問いかけ'),
  blank(),
  p('エマは後に、こう語っている。'),
  blank(),
  p('「サラは私の顔を知らなかった。', { italic: true }),
  p('私の名前も、私がどんな人間かも、知らなかった。', { italic: true }),
  p('それでも、あの夜の私を助けてくれた。', { italic: true }),
  blank(),
  p('世界には、そういう親切がある。', { italic: true }),
  p('名前のない、顔のない、見返りを求めない親切が。', { italic: true }),
  p('そしてそれは——気づかれなくても、ちゃんとそこにある」', { italic: true }),
  blank(),
  p('あなたの人生にも、「知らない誰かに助けられた」瞬間はありますか？'),
  blank(),
  p('誰かに席を譲ってもらった。'),
  p('転んだとき、知らない人が手を差し伸べた。'),
  p('道に迷っていたら、声をかけてもらった。'),
  blank(),
  p('その人たちは、あなたのことを今も知らない。'),
  p('でも、あなたの中に、確かに残っている。'),
  blank(),
  p('サラが本に書き込みをしたように——'),
  p('あなたも今日、誰かのための「余白の文字」を残せるかもしれない。', { bold: true }),
  blank(),
  p('特別なことじゃなくていい。'),
  p('ドアをそっと押さえる、それだけでもいい。'),
  p('エレベーターの「開」ボタンを少し長く押す、それだけでもいい。'),
  p('その小さな行動が、誰かの「あの夜」を救うかもしれない。'),
  blank(),
  p('あなたの人生で「名前を知らない誰かに助けられた」経験はありますか？'),
  p('あるいは——あなたが誰かのために、こっそり何かをした経験でも。'),
  p('ぜひコメント欄で教えてください。', { bold: true }),
  blank(),
  p('もし「誰かのために何かしたい」と思っている人が身近にいたら、'),
  p('この動画をそっと届けてあげてください。', { bold: true }),
  blank(),
  p('親切は、名前がなくても、ちゃんと届く。'),
  blank(),

  new Paragraph({ spacing: { before: 200, after: 80 },
    border: { top: { style: BorderStyle.SINGLE, size: 6, color: '2E4A7A', space: 4 } },
    children: [new TextRun({ text: 'このチャンネルでは、忙しい毎日の中で忘れかけている「大切なこと」をお届けしています。', font: 'Arial', size: 22, bold: true, color: '2E4A7A' })] }),
  new Paragraph({ spacing: { after: 80 },
    children: [new TextRun({ text: 'チャンネル登録とベルマークで、次の話もあなたのもとに届けます。', font: 'Arial', size: 22, bold: true, color: '2E4A7A' })] }),
  new Paragraph({ spacing: { after: 200 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '2E4A7A', space: 4 } },
    children: [new TextRun({ text: 'それではまた、心に響くお話でお会いしましょう。', font: 'Arial', size: 22, bold: true, color: '2E4A7A' })] }),
];

const doc = new Document({
  styles: {
    default: { document: { run: { font: 'Arial', size: 22 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 28, bold: true, font: 'Arial', color: '2E4A7A' },
        paragraph: { spacing: { before: 300, after: 160 }, outlineLevel: 0 } },
    ]
  },
  sections: [{
    properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
    children
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('/mnt/user-data/outputs/台本_余白の文字_v3.docx', buf);
  console.log('done');
});
